name: Release jenkins docker file

on:
  push:
    branches:
      - main

 pull-and-build-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2 

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: ast-plugin-jenkins
        pull-image: true