name: Release jenkins docker file
on:
  push:
    branches:
      - main
jobs:
  pull-and-build-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build . --tag ghcr.io/pedrompflopes/ast-jenkins-docker:latest
          docker run ghcr.io/pedrompflopes/ast-jenkins-docker:latest
          docker push ghcr.io/pedrompflopes/ast-jenkins-docker:latest
